### ISSUE TITLE
Neo4J fails to start with  Docker Run

### ISSUE THREAD

**Issue by masaver** [reactome/ReactomeGraph4R#25]
Hi All ,

I'm trying to get started with using ReactomeGraph4R, so I followed the installation instructions on github. While the reactome database is succesfully downloaded, when I execute the 'docker run' command  i get this message (see below).

Do any of you know why this error happens and how to solve it ?

Thanks a lot in advance !

-Mathias.

ERROR MESSAGE:

`Active database: graph.db
Directories in use:
  home:         /var/lib/neo4j
  config:       /var/lib/neo4j/conf
  logs:         /logs
  plugins:      /var/lib/neo4j/plugins
  import:       /var/lib/neo4j/import
  data:         /var/lib/neo4j/data
  certificates: /var/lib/neo4j/certificates
  run:          /var/lib/neo4j/run
Starting Neo4j.
2023-11-28 08:59:09.402+0000 WARN  Unknown config option: dbms.allow.upgrade
2023-11-28 08:59:09.412+0000 INFO  ======== Neo4j 3.5.19 ========
2023-11-28 08:59:09.417+0000 INFO  Starting...
2023-11-28 08:59:10.143+0000 ERROR Failed to start Neo4j: Starting Neo4j failed: Component 'org.neo4j.server.database.LifecycleManagingDatabase@42721fe' was successfully initialized, but failed to start. Please see the attached cause exception "Transaction logs contains entries with prefix 0, and the lowest supported prefix is 5. This indicates that the log files originates from an older version of neo4j, which we don't support migrations from.. At position LogPosition{logVersion=0, byteOffset=16} and entry version null". Starting Neo4j failed: Component 'org.neo4j.server.database.LifecycleManagingDatabase@42721fe' was successfully initialized, but failed to start. Please see the attached cause exception "Transaction logs contains entries with prefix 0, and the lowest supported prefix is 5. This indicates that the log files originates from an older version of neo4j, which we don't support migrations from.. At position LogPosition{logVersion=0, byteOffset=16} and entry version null".
org.neo4j.server.ServerStartupException: Starting Neo4j failed: Component 'org.neo4j.server.database.LifecycleManagingDatabase@42721fe' was successfully initialized, but failed to start. Please see the attached cause exception "Transaction logs contains entries with prefix 0, and the lowest supported prefix is 5. This indicates that the log files originates from an older version of neo4j, which we don't support migrations from.. At position LogPosition{logVersion=0, byteOffset=16} and entry version null".
        at org.neo4j.server.exception.ServerStartupErrors.translateToServerStartupError(ServerStartupErrors.java:45)
        at org.neo4j.server.AbstractNeoServer.start(AbstractNeoServer.java:187)
        at org.neo4j.server.ServerBootstrapper.start(ServerBootstrapper.java:124)
        at org.neo4j.server.ServerBootstrapper.start(ServerBootstrapper.java:91)
        at org.neo4j.server.CommunityEntryPoint.main(CommunityEntryPoint.java:32)
Caused by: org.neo4j.kernel.lifecycle.LifecycleException: Component 'org.neo4j.server.database.LifecycleManagingDatabase@42721fe' was successfully initialized, but failed to start. Please see the attached cause exception "Transaction logs contains entries with prefix 0, and the lowest supported prefix is 5. This indicates that the log files originates from an older version of neo4j, which we don't support migrations from.. At position LogPosition{logVersion=0, byteOffset=16} and entry version null".
        at org.neo4j.kernel.lifecycle.LifeSupport$LifecycleInstance.start(LifeSupport.java:473)
        at org.neo4j.kernel.lifecycle.LifeSupport.start(LifeSupport.java:111)
        at org.neo4j.server.AbstractNeoServer.start(AbstractNeoServer.java:180)
        ... 3 more
Caused by: java.lang.RuntimeException: Error starting org.neo4j.graphdb.facade.GraphDatabaseFacadeFactory, /data/databases
        at org.neo4j.graphdb.facade.GraphDatabaseFacadeFactory.initFacade(GraphDatabaseFacadeFactory.java:232)
        at org.neo4j.graphdb.facade.GraphDatabaseFacadeFactory.newFacade(GraphDatabaseFacadeFactory.java:148)
        at org.neo4j.server.database.CommunityGraphFactory.newGraphDatabase(CommunityGraphFactory.java:41)
        at org.neo4j.server.database.LifecycleManagingDatabase.start(LifecycleManagingDatabase.java:90)
        at org.neo4j.kernel.lifecycle.LifeSupport$LifecycleInstance.start(LifeSupport.java:452)
        ... 5 more
Caused by: org.neo4j.kernel.lifecycle.LifecycleException: Component 'org.neo4j.kernel.NeoStoreDataSource@9ef8eb7' was successfully initialized, but failed to start. Please see the attached cause exception "Transaction logs contains entries with prefix 0, and the lowest supported prefix is 5. This indicates that the log files originates from an older version of neo4j, which we don't support migrations from.. At position LogPosition{logVersion=0, byteOffset=16} and entry version null".
        at org.neo4j.kernel.lifecycle.LifeSupport$LifecycleInstance.start(LifeSupport.java:473)
        at org.neo4j.kernel.lifecycle.LifeSupport.start(LifeSupport.java:111)
        at org.neo4j.kernel.impl.transaction.state.DataSourceManager.start(DataSourceManager.java:116)
        at org.neo4j.kernel.lifecycle.LifeSupport$LifecycleInstance.start(LifeSupport.java:452)`

**Comment by chilampoon** [comment]
hi @masaver it seems like the neo4j version is not compatible, I guess you can try Neo4j v4
